# Generated by Django 4.1 on 2022-10-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_user_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
